### ISSUE TITLE
When can I see your paper

### ISSUE THREAD

**Issue by DuTim** [albanyan/hateful-tweets-replies#1]
dear author: 
   I don't find your paper in the Internet. When can I see your paper, I want to know more about the details of the paper. 
   Thanks !

**Comment by albanyan** [comment]
Hi
Here is the link for the paper. 
https://www.aaai.org/AAAI22Papers/AAAI-6353.AlbanyanA.pdf

The paper will be published soon by AAAI-22.

Thank you for the comment.

**Comment by albanyan** [comment]
https://www.aaai.org/AAAI22Papers/AAAI-6353.AlbanyanA.pdf
